apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bekaiym-biz-cert 
spec:
  secretName: bekaiym-biz-secret # your secret name
  dnsNames:
    - app.bekaiym.biz   
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer